kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cm-editor
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps"]
  verbs: ["get", "watch", "list", "create", "update"]
---
# This role binding allows "default" to read configmaps in the "default" namespace.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cm-editor
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: cm-editor
  apiGroup: rbac.authorization.k8s.io